[package]
name = "yew-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
gloo-dialogs = "0.2.0"
reqwasm = "0.5.0"
serde = { version = "1.0.195", features = ["derive"] }
wasm-bindgen-futures = "0.4.39"
web-sys = { version = "0.3.66", features = [
    "Element",
    "DomTokenList",
    "HtmlSelectElement",
] }
yew = { version = "0.21.0", features = ["csr"] }
types = { path = "../types" }
surrealdb = "1.0.0-beta.9"
log = "0.4.20"
wasm-logger = "0.2.0"
serde_json = "1.0"
uuid = { version = "1.6.1", features = ["v4"] }
